export type AvailabilityStatus = "live" | "scheduled" | "offline";
export type AccessMode = "spot" | "forward";

export interface ExpertListing {
  id: string;
  name: string;
  avatar: string;
  region: string;
  countryCode: string;
  timezone: string;
  languages: string[];
  categoryId: string;
  expertise: string[];
  headline: string;
  rating: number;
  sessionsCompleted: number;
  availabilityStatus: AvailabilityStatus;
  nextOpenSlot: string;
  responseTime: string;
  hourlyRate: number;
  verified: boolean;
  supportsInstant: boolean;
  supportsForwardOrders: boolean;
  bio: string;
}

export interface RegionDefinition {
  id: string;
  name: string;
  countryCode: string;
  timezone: string;
  coordinates: [number, number];
}

export interface RegionSummary extends RegionDefinition {
  expertCount: number;
  liveCount: number;
  forwardCount: number;
  dominantLanguages: string[];
  topExpertise: string[];
  minHourlyRate: number | null;
  maxHourlyRate: number | null;
}

export interface ExpertiseCategory {
  id: string;
  label: string;
  subcategories: string[];
}

export const EXPERTISE_MARKETS: ExpertiseCategory[] = [
  {
    id: "technology",
    label: "Technology",
    subcategories: [
      "Software Engineering",
      "Data Science",
      "AI / ML",
      "Cybersecurity",
      "Cloud / DevOps",
      "Product Management",
      "UI / UX",
    ],
  },
  {
    id: "finance",
    label: "Finance",
    subcategories: [
      "Quantitative Research",
      "Trading & Markets",
      "Investment Banking",
      "Private Equity",
      "Financial Modelling",
      "Accounting & Audit",
      "Fintech Strategy",
    ],
  },
  {
    id: "business-strategy",
    label: "Business & Strategy",
    subcategories: [
      "Management Consulting",
      "Business Strategy",
      "Operations",
      "Supply Chain",
      "Project Leadership",
    ],
  },
  {
    id: "education",
    label: "Education",
    subcategories: [
      "School Tutoring",
      "University Tutoring",
      "Exam Preparation",
      "Admissions Guidance",
      "Research Skills",
    ],
  },
  {
    id: "careers-interviews",
    label: "Careers & Interviews",
    subcategories: [
      "CV Review",
      "Behavioural Interviews",
      "Technical Interviews",
      "Assessment Centres",
      "Networking Strategy",
      "Personal Branding",
    ],
  },
  {
    id: "design-creative",
    label: "Design & Creative",
    subcategories: [
      "Brand Identity",
      "Product Design",
      "Graphic Design",
      "Motion Design",
      "Content Strategy",
    ],
  },
  {
    id: "languages-communication",
    label: "Languages & Communication",
    subcategories: [
      "English Speaking",
      "Business English",
      "Arabic",
      "Urdu",
      "French",
      "Public Speaking",
      "Presentation Skills",
    ],
  },
  {
    id: "health-wellbeing",
    label: "Health & Wellbeing",
    subcategories: [
      "Nutrition",
      "Fitness Coaching",
      "Mental Wellbeing",
      "Work-Life Balance",
    ],
  },
  {
    id: "productivity-life-skills",
    label: "Productivity & Life Skills",
    subcategories: [
      "Time Management",
      "Study Systems",
      "Career Planning",
      "Leadership Coaching",
      "Negotiation",
    ],
  },
  {
    id: "entrepreneurship",
    label: "Entrepreneurship",
    subcategories: [
      "Startup Strategy",
      "Fundraising & Pitch",
      "Growth Strategy",
      "Product-Market Fit",
      "Founder Operations",
    ],
  },
  {
    id: "law-policy",
    label: "Law & Policy",
    subcategories: [
      "Corporate Law",
      "IP & Patents",
      "Regulatory Compliance",
      "Public Policy",
      "Privacy & Data Governance",
    ],
  },
  {
    id: "sales-marketing",
    label: "Sales & Marketing",
    subcategories: [
      "B2B Sales",
      "Performance Marketing",
      "Demand Generation",
      "Brand Marketing",
      "Customer Success",
    ],
  },
];

export const ALL_EXPERTISE: string[] = EXPERTISE_MARKETS.flatMap(
  (category) => category.subcategories
);

export const SUBCATEGORY_TO_CATEGORY = Object.fromEntries(
  EXPERTISE_MARKETS.flatMap((category) =>
    category.subcategories.map((subcategory) => [subcategory, category.id])
  )
) as Record<string, string>;

export const CATEGORY_LABELS = Object.fromEntries(
  EXPERTISE_MARKETS.map((category) => [category.id, category.label])
) as Record<string, string>;

export const REGION_DEFINITIONS: RegionDefinition[] = [
  {
    id: "gb",
    name: "United Kingdom",
    countryCode: "GB",
    timezone: "GMT+0",
    coordinates: [-1.7, 53.2],
  },
  {
    id: "us",
    name: "United States",
    countryCode: "US",
    timezone: "GMT-5 to GMT-8",
    coordinates: [-98, 38.5],
  },
  {
    id: "in",
    name: "India",
    countryCode: "IN",
    timezone: "GMT+5:30",
    coordinates: [78.5, 22.5],
  },
  {
    id: "ae",
    name: "United Arab Emirates",
    countryCode: "AE",
    timezone: "GMT+4",
    coordinates: [54.2, 24.2],
  },
  {
    id: "de",
    name: "Germany",
    countryCode: "DE",
    timezone: "GMT+1",
    coordinates: [10.3, 51.1],
  },
  {
    id: "fr",
    name: "France",
    countryCode: "FR",
    timezone: "GMT+1",
    coordinates: [2.3, 46.8],
  },
  {
    id: "sg",
    name: "Singapore",
    countryCode: "SG",
    timezone: "GMT+8",
    coordinates: [103.82, 1.32],
  },
  {
    id: "jp",
    name: "Japan",
    countryCode: "JP",
    timezone: "GMT+9",
    coordinates: [138.5, 36.3],
  },
  {
    id: "br",
    name: "Brazil",
    countryCode: "BR",
    timezone: "GMT-3",
    coordinates: [-51.2, -14.3],
  },
  {
    id: "kr",
    name: "South Korea",
    countryCode: "KR",
    timezone: "GMT+9",
    coordinates: [127.8, 36.4],
  },
  {
    id: "sa",
    name: "Saudi Arabia",
    countryCode: "SA",
    timezone: "GMT+3",
    coordinates: [45.1, 23.9],
  },
  {
    id: "ng",
    name: "Nigeria",
    countryCode: "NG",
    timezone: "GMT+1",
    coordinates: [8.7, 9.1],
  },
];

export const COUNTRY_TO_REGION: Record<string, string> = {
  GBR: "gb",
  USA: "us",
  IND: "in",
  ARE: "ae",
  DEU: "de",
  FRA: "fr",
  SGP: "sg",
  JPN: "jp",
  BRA: "br",
  KOR: "kr",
  SAU: "sa",
  NGA: "ng",
};

export const EXPERT_LISTINGS: ExpertListing[] = [
  {
    id: "e1",
    name: "James Whitfield",
    avatar: "",
    region: "gb",
    countryCode: "GB",
    timezone: "GMT+0",
    languages: ["English"],
    categoryId: "finance",
    expertise: ["Quantitative Research", "Trading & Markets", "Fintech Strategy"],
    headline: "Cross-asset quant execution and derivatives advisor",
    rating: 4.9,
    sessionsCompleted: 342,
    availabilityStatus: "live",
    nextOpenSlot: "Today 18:30",
    responseTime: "< 5 min",
    hourlyRate: 165,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Former derivatives quant lead with 12 years across London trading infrastructure and pricing systems.",
  },
  {
    id: "e2",
    name: "Priya Sharma",
    avatar: "",
    region: "gb",
    countryCode: "GB",
    timezone: "GMT+0",
    languages: ["English", "Hindi"],
    categoryId: "technology",
    expertise: ["AI / ML", "Data Science", "Product Management"],
    headline: "Applied AI product and model delivery specialist",
    rating: 4.8,
    sessionsCompleted: 218,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Tue 15:00",
    responseTime: "15 min",
    hourlyRate: 128,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Research engineer turned product operator, focused on shipping AI systems into production teams.",
  },
  {
    id: "e3",
    name: "Michael Torres",
    avatar: "",
    region: "us",
    countryCode: "US",
    timezone: "GMT-5",
    languages: ["English", "Spanish"],
    categoryId: "entrepreneurship",
    expertise: ["Startup Strategy", "Fundraising & Pitch", "Founder Operations"],
    headline: "Operator for founder financing, board prep, and GTM resets",
    rating: 4.9,
    sessionsCompleted: 307,
    availabilityStatus: "live",
    nextOpenSlot: "Tomorrow 09:00",
    responseTime: "< 10 min",
    hourlyRate: 172,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Former COO and seed-stage advisor helping founders through financing, pricing, and operating cadence decisions.",
  },
  {
    id: "e4",
    name: "Sarah Kim",
    avatar: "",
    region: "us",
    countryCode: "US",
    timezone: "GMT-8",
    languages: ["English", "Korean"],
    categoryId: "design-creative",
    expertise: ["Product Design", "Brand Identity", "Content Strategy"],
    headline: "Design systems and brand clarity for product-led teams",
    rating: 4.8,
    sessionsCompleted: 261,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 11:00",
    responseTime: "30 min",
    hourlyRate: 136,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Product design lead with experience scaling consumer and fintech interfaces across web and mobile.",
  },
  {
    id: "e5",
    name: "Arjun Patel",
    avatar: "",
    region: "in",
    countryCode: "IN",
    timezone: "GMT+5:30",
    languages: ["English", "Hindi"],
    categoryId: "education",
    expertise: ["University Tutoring", "Exam Preparation", "Research Skills"],
    headline: "STEM tutoring and research methodology coaching",
    rating: 4.8,
    sessionsCompleted: 276,
    availabilityStatus: "live",
    nextOpenSlot: "Today 21:00",
    responseTime: "< 10 min",
    hourlyRate: 78,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Lead data scientist with a parallel practice in university-level tutoring, exam prep, and research coaching.",
  },
  {
    id: "e6",
    name: "Kavitha Rao",
    avatar: "",
    region: "in",
    countryCode: "IN",
    timezone: "GMT+5:30",
    languages: ["English", "Hindi"],
    categoryId: "careers-interviews",
    expertise: ["Technical Interviews", "CV Review", "Personal Branding"],
    headline: "Offer-ready interview loops for engineering careers",
    rating: 4.7,
    sessionsCompleted: 189,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Wed 14:30",
    responseTime: "20 min",
    hourlyRate: 68,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Former Amazon engineering interviewer running structured mock loops, CV review, and narrative positioning.",
  },
  {
    id: "e7",
    name: "Ahmed Al-Rashid",
    avatar: "",
    region: "ae",
    countryCode: "AE",
    timezone: "GMT+4",
    languages: ["English", "Arabic"],
    categoryId: "finance",
    expertise: ["Trading & Markets", "Financial Modelling", "Fintech Strategy"],
    headline: "Capital markets and fintech structuring for high-growth operators",
    rating: 4.8,
    sessionsCompleted: 167,
    availabilityStatus: "live",
    nextOpenSlot: "Tomorrow 16:00",
    responseTime: "< 5 min",
    hourlyRate: 182,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Former bank and exchange operator advising fintech launches, pricing models, and capital planning.",
  },
  {
    id: "e8",
    name: "Fatima Hassan",
    avatar: "",
    region: "ae",
    countryCode: "AE",
    timezone: "GMT+4",
    languages: ["English", "Arabic", "French"],
    categoryId: "law-policy",
    expertise: ["Regulatory Compliance", "Corporate Law", "Public Policy"],
    headline: "Regulatory route-mapping for cross-border launches",
    rating: 4.6,
    sessionsCompleted: 104,
    availabilityStatus: "offline",
    nextOpenSlot: "Fri 10:00",
    responseTime: "2 hrs",
    hourlyRate: 148,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Counsel and compliance advisor for digital products moving across MENA and European regulatory regimes.",
  },
  {
    id: "e9",
    name: "Max Bauer",
    avatar: "",
    region: "de",
    countryCode: "DE",
    timezone: "GMT+1",
    languages: ["German", "English"],
    categoryId: "business-strategy",
    expertise: ["Operations", "Supply Chain", "Project Leadership"],
    headline: "Execution-heavy operations coaching for scale-ups",
    rating: 4.9,
    sessionsCompleted: 231,
    availabilityStatus: "live",
    nextOpenSlot: "Fri 09:00",
    responseTime: "< 15 min",
    hourlyRate: 132,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Platform and operations leader focused on delivery systems, planning cadence, and cross-functional execution.",
  },
  {
    id: "e10",
    name: "Lena Fischer",
    avatar: "",
    region: "de",
    countryCode: "DE",
    timezone: "GMT+1",
    languages: ["German", "English", "French"],
    categoryId: "productivity-life-skills",
    expertise: ["Time Management", "Leadership Coaching", "Negotiation"],
    headline: "Performance systems for ambitious operators and managers",
    rating: 4.7,
    sessionsCompleted: 143,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 08:30",
    responseTime: "45 min",
    hourlyRate: 118,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Leadership coach helping founders and managers improve prioritisation, negotiation, and team operating rhythm.",
  },
  {
    id: "e11",
    name: "Antoine Dubois",
    avatar: "",
    region: "fr",
    countryCode: "FR",
    timezone: "GMT+1",
    languages: ["French", "English"],
    categoryId: "design-creative",
    expertise: ["Motion Design", "Graphic Design", "Brand Identity"],
    headline: "Visual storytelling for launches, decks, and premium brands",
    rating: 4.8,
    sessionsCompleted: 198,
    availabilityStatus: "live",
    nextOpenSlot: "Tomorrow 11:00",
    responseTime: "< 20 min",
    hourlyRate: 124,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Creative director working across motion, identity, and investor storytelling for European tech teams.",
  },
  {
    id: "e12",
    name: "Amelie Laurent",
    avatar: "",
    region: "fr",
    countryCode: "FR",
    timezone: "GMT+1",
    languages: ["French", "English"],
    categoryId: "languages-communication",
    expertise: ["French", "Business English", "Presentation Skills"],
    headline: "High-stakes communication coaching across English and French",
    rating: 4.7,
    sessionsCompleted: 121,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Tue 17:30",
    responseTime: "25 min",
    hourlyRate: 96,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Speech and communication coach for operators preparing investor, client, and internal presentations.",
  },
  {
    id: "e13",
    name: "Wei Lin Tan",
    avatar: "",
    region: "sg",
    countryCode: "SG",
    timezone: "GMT+8",
    languages: ["English", "Mandarin", "Malay"],
    categoryId: "finance",
    expertise: ["Quantitative Research", "Trading & Markets", "Financial Modelling"],
    headline: "Asia market structure and quant systems advisor",
    rating: 4.9,
    sessionsCompleted: 289,
    availabilityStatus: "live",
    nextOpenSlot: "Today 20:00",
    responseTime: "< 5 min",
    hourlyRate: 188,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Quant VP with experience in market structure, intraday risk tooling, and execution analytics.",
  },
  {
    id: "e14",
    name: "Aisha Binte Rahman",
    avatar: "",
    region: "sg",
    countryCode: "SG",
    timezone: "GMT+8",
    languages: ["English", "Malay"],
    categoryId: "sales-marketing",
    expertise: ["Demand Generation", "Brand Marketing", "Customer Success"],
    headline: "Demand and expansion strategy for B2B platforms",
    rating: 4.7,
    sessionsCompleted: 112,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 15:00",
    responseTime: "35 min",
    hourlyRate: 110,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Commercial operator advising on demand capture, onboarding systems, and lifecycle growth for SaaS teams.",
  },
  {
    id: "e15",
    name: "Yuki Tanaka",
    avatar: "",
    region: "jp",
    countryCode: "JP",
    timezone: "GMT+9",
    languages: ["Japanese", "English"],
    categoryId: "technology",
    expertise: ["Software Engineering", "Product Management", "UI / UX"],
    headline: "Product execution and mobile delivery specialist",
    rating: 4.8,
    sessionsCompleted: 167,
    availabilityStatus: "live",
    nextOpenSlot: "Wed 13:00",
    responseTime: "< 15 min",
    hourlyRate: 138,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Mobile product lead who helps teams tighten product scope, interaction quality, and shipping discipline.",
  },
  {
    id: "e16",
    name: "Naoko Sato",
    avatar: "",
    region: "jp",
    countryCode: "JP",
    timezone: "GMT+9",
    languages: ["Japanese", "English"],
    categoryId: "health-wellbeing",
    expertise: ["Mental Wellbeing", "Work-Life Balance", "Fitness Coaching"],
    headline: "Performance and wellbeing coaching for high-output professionals",
    rating: 4.6,
    sessionsCompleted: 87,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Fri 07:30",
    responseTime: "1 hr",
    hourlyRate: 92,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Executive wellbeing coach blending behavioural routines, recovery planning, and performance sustainability.",
  },
  {
    id: "e17",
    name: "Lucas Silva",
    avatar: "",
    region: "br",
    countryCode: "BR",
    timezone: "GMT-3",
    languages: ["Portuguese", "English", "Spanish"],
    categoryId: "entrepreneurship",
    expertise: ["Growth Strategy", "Product-Market Fit", "Startup Strategy"],
    headline: "Growth and GTM advisor for product-led startups",
    rating: 4.7,
    sessionsCompleted: 145,
    availabilityStatus: "live",
    nextOpenSlot: "Today 19:30",
    responseTime: "< 10 min",
    hourlyRate: 98,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Former startup operator helping founders sharpen market selection, GTM motion, and retention loops.",
  },
  {
    id: "e18",
    name: "Mariana Costa",
    avatar: "",
    region: "br",
    countryCode: "BR",
    timezone: "GMT-3",
    languages: ["Portuguese", "English"],
    categoryId: "sales-marketing",
    expertise: ["B2B Sales", "Performance Marketing", "Customer Success"],
    headline: "Revenue systems coach from first pipeline to expansion",
    rating: 4.6,
    sessionsCompleted: 103,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 16:00",
    responseTime: "40 min",
    hourlyRate: 88,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Commercial leader working across B2B sales process, paid growth, and account expansion systems.",
  },
  {
    id: "e19",
    name: "Jisoo Park",
    avatar: "",
    region: "kr",
    countryCode: "KR",
    timezone: "GMT+9",
    languages: ["Korean", "English"],
    categoryId: "technology",
    expertise: ["AI / ML", "Data Science", "Cloud / DevOps"],
    headline: "Production AI architecture and MLOps specialist",
    rating: 4.8,
    sessionsCompleted: 201,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Fri 14:00",
    responseTime: "50 min",
    hourlyRate: 126,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "ML researcher and platform builder focused on deployment reliability, inference cost, and model operations.",
  },
  {
    id: "e20",
    name: "Minseo Choi",
    avatar: "",
    region: "kr",
    countryCode: "KR",
    timezone: "GMT+9",
    languages: ["Korean", "English"],
    categoryId: "education",
    expertise: ["Admissions Guidance", "University Tutoring", "Research Skills"],
    headline: "Admissions and academic strategy for competitive programmes",
    rating: 4.7,
    sessionsCompleted: 118,
    availabilityStatus: "offline",
    nextOpenSlot: "Mon 10:00",
    responseTime: "3 hrs",
    hourlyRate: 86,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Academic advisor supporting application narratives, research planning, and structured study strategy.",
  },
  {
    id: "e21",
    name: "Omar Al-Zahrani",
    avatar: "",
    region: "sa",
    countryCode: "SA",
    timezone: "GMT+3",
    languages: ["Arabic", "English"],
    categoryId: "law-policy",
    expertise: ["Privacy & Data Governance", "Regulatory Compliance", "Public Policy"],
    headline: "Policy and governance advisor for digital infrastructure teams",
    rating: 4.6,
    sessionsCompleted: 67,
    availabilityStatus: "offline",
    nextOpenSlot: "Tomorrow 10:00",
    responseTime: "90 min",
    hourlyRate: 144,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Governance and compliance specialist working on data policies, vendor controls, and public-sector frameworks.",
  },
  {
    id: "e22",
    name: "Layla Al-Harbi",
    avatar: "",
    region: "sa",
    countryCode: "SA",
    timezone: "GMT+3",
    languages: ["Arabic", "English", "Urdu"],
    categoryId: "languages-communication",
    expertise: ["Arabic", "Urdu", "Public Speaking"],
    headline: "Multilingual communication coaching for cross-border operators",
    rating: 4.7,
    sessionsCompleted: 94,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 12:00",
    responseTime: "25 min",
    hourlyRate: 94,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Language and communication coach helping teams handle multilingual meetings, pitches, and partner conversations.",
  },
  {
    id: "e23",
    name: "Adebayo Okonkwo",
    avatar: "",
    region: "ng",
    countryCode: "NG",
    timezone: "GMT+1",
    languages: ["English"],
    categoryId: "careers-interviews",
    expertise: ["Networking Strategy", "Behavioural Interviews", "CV Review"],
    headline: "Career positioning and interview strategy for high-growth roles",
    rating: 4.7,
    sessionsCompleted: 156,
    availabilityStatus: "live",
    nextOpenSlot: "Today 17:30",
    responseTime: "< 10 min",
    hourlyRate: 72,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Career strategist supporting role transitions, narrative framing, and high-signal networking outreach.",
  },
  {
    id: "e24",
    name: "Chioma Nwosu",
    avatar: "",
    region: "ng",
    countryCode: "NG",
    timezone: "GMT+1",
    languages: ["English"],
    categoryId: "productivity-life-skills",
    expertise: ["Career Planning", "Study Systems", "Time Management"],
    headline: "Planning systems for ambitious builders and career switchers",
    rating: 4.5,
    sessionsCompleted: 92,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Wed 19:00",
    responseTime: "35 min",
    hourlyRate: 62,
    verified: false,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Coach focused on study systems, career planning, and disciplined routines for multi-track professionals.",
  },
  {
    id: "e25",
    name: "Oliver Hargreaves",
    avatar: "",
    region: "gb",
    countryCode: "GB",
    timezone: "GMT+0",
    languages: ["English"],
    categoryId: "technology",
    expertise: ["Software Engineering", "Cloud / DevOps", "Cybersecurity"],
    headline: "Infrastructure and platform reliability engineering",
    rating: 4.8,
    sessionsCompleted: 195,
    availabilityStatus: "live",
    nextOpenSlot: "Today 16:00",
    responseTime: "< 10 min",
    hourlyRate: 142,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Site reliability and platform engineer helping teams build robust infrastructure and incident response.",
  },
  {
    id: "e26",
    name: "Hannah Clarke",
    avatar: "",
    region: "gb",
    countryCode: "GB",
    timezone: "GMT+0",
    languages: ["English"],
    categoryId: "business-strategy",
    expertise: ["Management Consulting", "Business Strategy", "Project Leadership"],
    headline: "Strategy consulting for mid-market growth operators",
    rating: 4.7,
    sessionsCompleted: 163,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Wed 10:00",
    responseTime: "30 min",
    hourlyRate: 155,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Former McKinsey engagement manager advising on growth strategy, org design, and execution planning.",
  },
  {
    id: "e27",
    name: "David Park",
    avatar: "",
    region: "us",
    countryCode: "US",
    timezone: "GMT-5",
    languages: ["English", "Korean"],
    categoryId: "technology",
    expertise: ["AI / ML", "Data Science", "Software Engineering"],
    headline: "ML systems architect and research-to-production specialist",
    rating: 4.9,
    sessionsCompleted: 284,
    availabilityStatus: "live",
    nextOpenSlot: "Today 14:00",
    responseTime: "< 5 min",
    hourlyRate: 195,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Staff ML engineer specialising in large-scale inference systems, model serving, and research operationalisation.",
  },
  {
    id: "e28",
    name: "Rachel Nguyen",
    avatar: "",
    region: "us",
    countryCode: "US",
    timezone: "GMT-8",
    languages: ["English", "Vietnamese"],
    categoryId: "finance",
    expertise: ["Investment Banking", "Financial Modelling", "Private Equity"],
    headline: "Investment banking and deal execution advisor",
    rating: 4.8,
    sessionsCompleted: 178,
    availabilityStatus: "live",
    nextOpenSlot: "Tomorrow 11:00",
    responseTime: "< 15 min",
    hourlyRate: 185,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Former Goldman Sachs VP advising on deal structuring, financial modelling, and capital markets strategy.",
  },
  {
    id: "e29",
    name: "Emily Chen",
    avatar: "",
    region: "us",
    countryCode: "US",
    timezone: "GMT-5",
    languages: ["English", "Mandarin"],
    categoryId: "careers-interviews",
    expertise: ["Technical Interviews", "CV Review", "Assessment Centres"],
    headline: "Big Tech interview coaching and career strategy",
    rating: 4.7,
    sessionsCompleted: 312,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 09:00",
    responseTime: "20 min",
    hourlyRate: 115,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Former Meta interviewer running structured loops, system design prep, and senior-level positioning.",
  },
  {
    id: "e30",
    name: "Ravi Krishnamurthy",
    avatar: "",
    region: "in",
    countryCode: "IN",
    timezone: "GMT+5:30",
    languages: ["English", "Hindi", "Tamil"],
    categoryId: "technology",
    expertise: ["Cloud / DevOps", "Software Engineering", "Cybersecurity"],
    headline: "Cloud architecture and DevOps transformation advisor",
    rating: 4.8,
    sessionsCompleted: 247,
    availabilityStatus: "live",
    nextOpenSlot: "Today 22:00",
    responseTime: "< 10 min",
    hourlyRate: 85,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Principal cloud architect with deep AWS and GCP expertise, helping teams modernise infrastructure.",
  },
  {
    id: "e31",
    name: "Sunita Desai",
    avatar: "",
    region: "in",
    countryCode: "IN",
    timezone: "GMT+5:30",
    languages: ["English", "Hindi", "Marathi"],
    categoryId: "entrepreneurship",
    expertise: ["Startup Strategy", "Product-Market Fit", "Fundraising & Pitch"],
    headline: "Early-stage startup operator and pitch advisor",
    rating: 4.6,
    sessionsCompleted: 132,
    availabilityStatus: "live",
    nextOpenSlot: "Today 20:30",
    responseTime: "< 15 min",
    hourlyRate: 72,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Two-time founder turned advisor, helping early-stage teams find product-market fit and raise seed rounds.",
  },
  {
    id: "e32",
    name: "Deepak Mehta",
    avatar: "",
    region: "in",
    countryCode: "IN",
    timezone: "GMT+5:30",
    languages: ["English", "Hindi"],
    categoryId: "finance",
    expertise: ["Fintech Strategy", "Financial Modelling", "Trading & Markets"],
    headline: "Fintech product strategy and financial systems design",
    rating: 4.7,
    sessionsCompleted: 189,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Fri 11:00",
    responseTime: "25 min",
    hourlyRate: 92,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Payments and lending product leader with experience across UPI, BNPL, and digital banking systems.",
  },
  {
    id: "e33",
    name: "Daniel Weber",
    avatar: "",
    region: "de",
    countryCode: "DE",
    timezone: "GMT+1",
    languages: ["German", "English"],
    categoryId: "technology",
    expertise: ["Software Engineering", "Product Management", "Cloud / DevOps"],
    headline: "Engineering leadership and team scaling advisor",
    rating: 4.8,
    sessionsCompleted: 205,
    availabilityStatus: "live",
    nextOpenSlot: "Today 17:00",
    responseTime: "< 10 min",
    hourlyRate: 148,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "VP Engineering helping scale engineering orgs, improve delivery velocity, and establish technical strategy.",
  },
  {
    id: "e34",
    name: "Claire Dupont",
    avatar: "",
    region: "fr",
    countryCode: "FR",
    timezone: "GMT+1",
    languages: ["French", "English", "Spanish"],
    categoryId: "sales-marketing",
    expertise: ["Brand Marketing", "Performance Marketing", "Demand Generation"],
    headline: "Growth marketing and brand strategy for European expansion",
    rating: 4.7,
    sessionsCompleted: 156,
    availabilityStatus: "live",
    nextOpenSlot: "Tomorrow 10:00",
    responseTime: "< 20 min",
    hourlyRate: 118,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Growth and brand operator helping B2B companies launch and scale across European markets.",
  },
  {
    id: "e35",
    name: "Kenji Yamamoto",
    avatar: "",
    region: "jp",
    countryCode: "JP",
    timezone: "GMT+9",
    languages: ["Japanese", "English"],
    categoryId: "design-creative",
    expertise: ["Product Design", "UI / UX", "Brand Identity"],
    headline: "Product design and interaction quality specialist",
    rating: 4.9,
    sessionsCompleted: 178,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Thu 14:00",
    responseTime: "40 min",
    hourlyRate: 152,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Design director focused on interaction design, design systems, and premium digital product craft.",
  },
  {
    id: "e36",
    name: "Hassan Al-Farsi",
    avatar: "",
    region: "ae",
    countryCode: "AE",
    timezone: "GMT+4",
    languages: ["Arabic", "English"],
    categoryId: "entrepreneurship",
    expertise: ["Growth Strategy", "Founder Operations", "Startup Strategy"],
    headline: "MENA startup ecosystem advisor and growth operator",
    rating: 4.7,
    sessionsCompleted: 124,
    availabilityStatus: "live",
    nextOpenSlot: "Today 19:00",
    responseTime: "< 10 min",
    hourlyRate: 158,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Serial operator and investor advisor helping startups navigate MENA market entry and fundraising.",
  },
  {
    id: "e37",
    name: "Mei Ling Tan",
    avatar: "",
    region: "sg",
    countryCode: "SG",
    timezone: "GMT+8",
    languages: ["English", "Mandarin"],
    categoryId: "law-policy",
    expertise: ["IP & Patents", "Corporate Law", "Privacy & Data Governance"],
    headline: "IP and tech law advisor for APAC digital products",
    rating: 4.6,
    sessionsCompleted: 98,
    availabilityStatus: "live",
    nextOpenSlot: "Today 21:00",
    responseTime: "< 15 min",
    hourlyRate: 168,
    verified: true,
    supportsInstant: true,
    supportsForwardOrders: true,
    bio: "Technology lawyer advising on IP protection, data governance, and cross-border compliance for APAC startups.",
  },
  {
    id: "e38",
    name: "Isabella Santos",
    avatar: "",
    region: "br",
    countryCode: "BR",
    timezone: "GMT-3",
    languages: ["Portuguese", "English", "Spanish"],
    categoryId: "design-creative",
    expertise: ["Brand Identity", "Graphic Design", "Content Strategy"],
    headline: "Brand and visual identity for LatAm tech companies",
    rating: 4.7,
    sessionsCompleted: 134,
    availabilityStatus: "scheduled",
    nextOpenSlot: "Wed 15:00",
    responseTime: "30 min",
    hourlyRate: 82,
    verified: true,
    supportsInstant: false,
    supportsForwardOrders: true,
    bio: "Brand designer and creative director helping tech companies build distinctive visual identities.",
  },
];

export const ALL_LANGUAGES = Array.from(
  new Set(EXPERT_LISTINGS.flatMap((listing) => listing.languages))
).sort((a, b) => a.localeCompare(b));

export function getRegionDefinitionById(
  regionId: string
): RegionDefinition | undefined {
  return REGION_DEFINITIONS.find((region) => region.id === regionId);
}

export function getCategoryById(categoryId: string): ExpertiseCategory | undefined {
  return EXPERTISE_MARKETS.find((category) => category.id === categoryId);
}

export function getRegionSummaries(
  listings: ExpertListing[] = EXPERT_LISTINGS
): RegionSummary[] {
  return REGION_DEFINITIONS.map((region) => {
    const regionListings = listings.filter((listing) => listing.region === region.id);
    const dominantLanguages = Array.from(
      new Set(regionListings.flatMap((listing) => listing.languages))
    ).slice(0, 3);

    const topExpertise = Array.from(
      regionListings
        .reduce<Map<string, number>>((counts, listing) => {
          listing.expertise.forEach((tag) => {
            counts.set(tag, (counts.get(tag) ?? 0) + 1);
          });
          return counts;
        }, new Map())
        .entries()
    )
      .sort((a, b) => b[1] - a[1])
      .slice(0, 3)
      .map(([tag]) => tag);

    const rates = regionListings.map((listing) => listing.hourlyRate);

    return {
      ...region,
      expertCount: regionListings.length,
      liveCount: regionListings.filter(
        (listing) => listing.availabilityStatus === "live"
      ).length,
      forwardCount: regionListings.filter(
        (listing) => listing.supportsForwardOrders
      ).length,
      dominantLanguages,
      topExpertise,
      minHourlyRate: rates.length ? Math.min(...rates) : null,
      maxHourlyRate: rates.length ? Math.max(...rates) : null,
    };
  });
}
